// List of all 25+ modules for the Module Marketplace
export default [
  { key: 'project-overview', name: 'Project Overview & Analytics', icon: '📊' },
  { key: 'daily-reports', name: 'Daily Reports', icon: '📝' },
  { key: 'qaqc-reports', name: 'QA/QC Reports', icon: '🧪' },
  { key: 'hse-observations', name: 'HSE Observations', icon: '🦺' },
  { key: 'submittals', name: 'Submittals', icon: '📤' },
  { key: 'rfi-management', name: 'RFI Management', icon: '❓' },
  { key: 'boq-quantity', name: 'BOQ & Quantity Survey', icon: '📋' },
  { key: 'material-logs', name: 'Material Logs', icon: '📦' },
  { key: 'document-control', name: 'Document Control', icon: '📁' },
  { key: 'specifications', name: 'Specifications', icon: '📄' },
  { key: 'meeting-minutes', name: 'Meeting Minutes', icon: '🗒️' },
  { key: 'progress-schedule', name: 'Progress Schedule & Gantt', icon: '📆' },
  { key: 'timesheets', name: 'Timesheets', icon: '⏱️' },
  { key: 'attendance', name: 'Attendance', icon: '🧑‍💼' },
  { key: 'media-gallery', name: 'Media Gallery', icon: '🖼️' },
  { key: 'issue-tracker', name: 'Issue Tracker', icon: '📌' },
  { key: 'toolbox-talks', name: 'Toolbox Talks', icon: '🧰' },
  { key: 'asset-register', name: 'Asset Register', icon: '📒' },
  { key: 'procurement', name: 'Procurement', icon: '🛒' },
  { key: 'contract-management', name: 'Contract Management', icon: '📑' },
  { key: 'change-orders', name: 'Change Orders', icon: '🔄' },
  { key: 'payment-apps', name: 'Payment Applications', icon: '💵' },
  { key: 'equipment-management', name: 'Equipment Management', icon: '🚜' },
  { key: 'workforce-management', name: 'Workforce Management', icon: '👷' },
  { key: 'training', name: 'Training', icon: '🎓' },
  { key: 'risk-assessment', name: 'Risk Assessment', icon: '⚠️' },
  { key: 'audit-logs', name: 'Audit Logs', icon: '📝' },
  { key: 'client-communication', name: 'Client Communication', icon: '💬' },
  { key: 'mobile-tools', name: 'Mobile Field Tools', icon: '📱' },
  { key: 'integration', name: 'Integration Modules', icon: '🔗' },
  { key: 'custom-module', name: 'Custom Module Builder', icon: '🛠️' },
];
