// Role-based sidebar config for Construction IMS
import { FaUsers, FaCog, FaClipboardList, FaTools, FaUpload, FaCalendarAlt, FaRegFileAlt, FaChartBar, FaFileAlt, FaRegClock, FaRegUser, FaQuestionCircle, FaFireExtinguisher, FaFolderOpen, FaMoneyBillWave, FaHardHat, FaCheckCircle, FaProjectDiagram, FaBoxOpen, FaUserCheck, FaCamera, FaThumbtack, FaWrench, FaCogs } from 'react-icons/fa';

export const roleSidebarConfig = {
  Admin: [
    { label: 'User Management', icon: FaUsers, route: 'users' },
    { label: 'System Settings', icon: FaCog, route: 'settings' },
    { label: 'All Modules', icon: FaClipboardList, route: 'modules' },
    { label: 'Approval Panel', icon: FaCheckCircle, route: 'approvals' },
    { label: 'Audit Log', icon: FaClipboardList, route: 'audit-log' },
    { label: 'Project Configuration', icon: FaChartBar, route: 'projects' },
    { label: 'QA/QC', icon: FaTools, route: '/dashboard/qaqc' },
  ],
  pm: [
    { label: 'Dashboard Home', icon: FaProjectDiagram, route: '/dashboard/pm/home' },
    { label: 'Daily Reports', icon: FaClipboardList, route: '/dashboard/pm/daily-reports' },
    { label: 'QA/QC (NCRs, Checklists, Punch Lists)', icon: FaTools, route: '/dashboard/pm/qaqc' },
    { label: 'HSE Reports (Incidents, Observations, OSHA Logs)', icon: FaFireExtinguisher, route: '/dashboard/pm/hse' },
    { label: 'Submittals', icon: FaUpload, route: '/dashboard/pm/submittals' },
    { label: 'RFIs', icon: FaQuestionCircle, route: '/dashboard/pm/rfis' },
    { label: 'BOQ / Quantity Survey', icon: FaChartBar, route: '/dashboard/pm/boq' },
    { label: 'Schedule (Gantt View, Milestones)', icon: FaCalendarAlt, route: '/dashboard/pm/schedule' },
    { label: 'Meetings (Minutes, Action Items)', icon: FaRegFileAlt, route: '/dashboard/pm/meetings' },
    { label: 'Document Control (Uploads, Versioning)', icon: FaFolderOpen, route: '/dashboard/pm/document-control' },
    { label: 'Material Logs', icon: FaBoxOpen, route: '/dashboard/pm/material-logs' },
    { label: 'Specifications & Standards', icon: FaFileAlt, route: '/dashboard/pm/specifications' },
    { label: 'Project KPIs', icon: FaChartBar, route: '/dashboard/pm/kpis' },
    { label: 'Approvals (Pending Workflows)', icon: FaCheckCircle, route: '/dashboard/pm/approvals' },
    { label: 'Timesheets', icon: FaRegClock, route: '/dashboard/pm/timesheets' },
    { label: 'Attendance Tracker', icon: FaUserCheck, route: '/dashboard/pm/attendance' },
    { label: 'Media Gallery', icon: FaCamera, route: '/dashboard/pm/media-gallery' },
    { label: 'Issue Tracker', icon: FaThumbtack, route: '/dashboard/pm/issues' },
    { label: 'Toolbox Talks', icon: FaWrench, route: '/dashboard/pm/toolbox-talks' },
    { label: 'Asset Register', icon: FaCogs, route: '/dashboard/pm/assets' },
    { label: 'User Management', icon: FaUsers, route: '/dashboard/pm/user-management' },
    { label: 'Settings', icon: FaCog, route: '/dashboard/pm/settings' },
    { label: 'QA/QC', icon: FaTools, route: '/dashboard/qaqc' },
  ],
  'QA/QC Engineer': [
    { label: 'QA/QC Reports', icon: FaTools, route: '/dashboard/qaqc/reports' },
    { label: 'NCRs', icon: FaChartBar, route: '/dashboard/qaqc/ncrs' },
    { label: 'Inspection Checklists', icon: FaCheckCircle, route: '/dashboard/qaqc/checklists' },
    { label: 'Submittals', icon: FaUpload, route: '/dashboard/qaqc/submittals' },
    { label: 'Daily Reports', icon: FaClipboardList, route: '/dashboard/qaqc/daily-reports' },
    { label: 'QA/QC Dashboard', icon: FaTools, route: '/dashboard/qaqc/home' },
    { label: 'Summary Reports', icon: FaChartBar, route: '/dashboard/qaqc/summary-reports' },
    { label: 'QA/QC', icon: FaTools, route: '/dashboard/qaqc' },
  ],
  'HSE Officer': [
    { label: 'HSE Reports', icon: FaFireExtinguisher, route: '/dashboard/hse/reports' },
    { label: 'Safety Observations', icon: FaHardHat, route: '/dashboard/hse/observations' },
    { label: 'Incident Logs', icon: FaRegFileAlt, route: '/dashboard/hse/incidents' },
    { label: 'Toolbox Talks', icon: FaRegUser, route: '/dashboard/hse/toolbox-talks' },
  ],
  'Document Controller': [
    { label: 'Submittals', icon: FaUpload, route: '/dashboard/docs/submittals' },
    { label: 'Document Library', icon: FaFolderOpen, route: '/dashboard/docs/library' },
    { label: 'Revision Tracking', icon: FaFileAlt, route: '/dashboard/docs/revisions' },
  ],
  'Cost Engineer': [
    { label: 'BOQ', icon: FaChartBar, route: '/dashboard/finance/boq' },
    { label: 'Quantity Survey', icon: FaClipboardList, route: '/dashboard/finance/quantity-survey' },
    { label: 'Cost Logs', icon: FaMoneyBillWave, route: '/dashboard/finance/cost-logs' },
    { label: 'Payment Tracking', icon: FaRegClock, route: '/dashboard/finance/payments' },
  ],
  'Client / Owner': [
    { label: 'Project Overview', icon: FaChartBar, route: '/dashboard/client/overview' },
    { label: 'Reports', icon: FaClipboardList, route: '/dashboard/client/reports' },
    { label: 'Submittal Status', icon: FaUpload, route: '/dashboard/client/submittals' },
    { label: 'Financials', icon: FaMoneyBillWave, route: '/dashboard/client/financials' },
  ],
  'Scheduler / Planner': [
    { label: 'Gantt View', icon: FaChartBar, route: '/dashboard/schedule/gantt' },
    { label: 'Milestones', icon: FaCheckCircle, route: '/dashboard/schedule/milestones' },
    { label: 'Progress Logs', icon: FaChartBar, route: '/dashboard/schedule/progress' },
  ],
  'Site Supervisor': [
    { label: 'Daily Reports', icon: FaClipboardList, route: '/dashboard/site/daily-reports' },
    { label: 'Manpower', icon: FaUsers, route: '/dashboard/site/manpower' },
    { label: 'Equipment Logs', icon: FaTools, route: '/dashboard/site/equipment' },
    { label: 'Work Execution Logs', icon: FaRegFileAlt, route: '/dashboard/site/work-logs' },
  ],
  superintendent: [
    { label: 'Daily Reports', icon: FaClipboardList, route: '/dashboard/superintendent/daily-reports' },
    { label: 'Superintendent Dashboard', icon: FaHardHat, route: '/dashboard/superintendent/home' },
  ],
};
